# Generated by Django 5.2.5 on 2025-08-29 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveIndex(
            model_name='battery',
            name='batteries_b_categor_3f9eba_idx',
        ),
        migrations.RemoveField(
            model_name='battery',
            name='category',
        ),
        migrations.AddField(
            model_name='battery',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Multiple categories (vehicle type, battery type, use case)', related_name='batteries', to='batteries.category'),
        ),
        migrations.AddField(
            model_name='battery',
            name='compatible_vehicles',
            field=models.JSONField(blank=True, default=list, help_text="List of compatible vehicle models e.g., ['Toyota Vitz', 'Mazda Demio', 'Nissan March']"),
        ),
        migrations.AddField(
            model_name='battery',
            name='vehicle_makes',
            field=models.JSONField(blank=True, default=list, help_text="List of vehicle makes e.g., ['Toyota', 'Mazda', 'Nissan']"),
        ),
        migrations.AddField(
            model_name='battery',
            name='vehicle_models',
            field=models.JSONField(blank=True, default=list, help_text="List of specific models e.g., ['Vitz', 'Demio', 'March']"),
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark as popular brand'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('vehicle_type', 'Vehicle Type'), ('battery_type', 'Battery Type'), ('use_case', 'Use Case'), ('brand_series', 'Brand Series')], default='vehicle_type', help_text='Type of categorization this represents', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='For hierarchical categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='batteries.category'),
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['price', 'is_active'], name='batteries_b_price_72e4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='battery',
            index=models.Index(fields=['voltage', 'is_active'], name='batteries_b_voltage_cd68d2_idx'),
        ),
    ]
